import type {
  AgentAst,
  FieldDecl,
  PromptSegment,
  ToaType,
  ToolDecl,
} from "./ast.js";

/**
 * Emit a readable, typed TypeScript module from an `AgentAst`. Output is
 * deterministic (same AST -> byte-identical code) and matches the contract in
 * `_bmad-output/architecture.md` §5. The emitted module imports its tools from
 * the co-located `<name>.tools` file and the loop from `toad-runtime`.
 */
export function generate(ast: AgentAst): string {
  const pascal = pascalCase(ast.name);
  const inputType = `${pascal}Input`;
  const outputType = `${pascal}Output`;
  const hasInputs = ast.inputs.length > 0;
  const hasOutputs = ast.outputs.length > 0;
  const hasTools = ast.tools.length > 0;
  // Typed tools (the tabular form) carry an input schema the compiler owns and
  // wires into a `defineTool`; bare tools import a ready-made `ToolDef`.
  const typedTools = ast.tools.filter((t) => t.input !== undefined);
  const agentType = `Agent<${inputType}, ${hasOutputs ? outputType : "string"}>`;

  // Resolve interpolation types up front so non-scalar values (objects/arrays)
  // render as TOON via `toonValue(...)` instead of the useless `[object
  // Object]`. Scalar interpolations stay byte-identical to plain `${...}`.
  const ctx: EmitCtx = {
    inputTypes: new Map(ast.inputs.map((f) => [f.name, f.type])),
    optionalInputs: new Set(
      ast.inputs.filter((f) => f.optional === true).map((f) => f.name),
    ),
    usesToon: false,
  };
  const promptCode = promptExpr(ast.prompt, ctx, new Map());
  const systemCode = ast.system
    ? promptExpr(ast.system, ctx, new Map())
    : undefined;

  const needsZod = hasInputs || hasOutputs || typedTools.length > 0;

  const lines: string[] = [];
  lines.push(`// Generated by toac from ${ast.name}.agent — do not edit.`);
  const runtimeImports = ["createAgent"];
  if (typedTools.length > 0) runtimeImports.push("defineTool");
  if (ctx.usesToon) runtimeImports.push("toonValue");
  lines.push(
    `import { ${runtimeImports.join(", ")}, type Agent } from "toad-runtime";`,
  );
  if (needsZod) {
    lines.push(`import { z } from "zod";`);
  }
  if (hasTools) {
    lines.push(
      `import { ${ast.tools.map((t) => t.name).join(", ")} } from "./${ast.name}.tools";`,
    );
  }
  for (const sub of ast.uses) {
    lines.push(`import { ${sub} } from "./${sub}";`);
  }
  lines.push("");

  emitInterface(lines, inputType, ast.inputs);
  lines.push("");

  if (hasOutputs) {
    emitInterface(lines, outputType, ast.outputs);
    lines.push("");
  }

  // One exported input interface per typed tool, so the `.tools.ts` body can
  // type its parameter (`(input: WebSearchInput) => …`).
  for (const t of typedTools) {
    emitInterface(lines, `${pascalCase(t.name)}Input`, t.input!.fields ?? []);
    lines.push("");
  }

  if (hasInputs) {
    emitSchema(lines, "inputSchema", ast.inputs);
    lines.push("");
  }

  if (hasOutputs) {
    emitSchema(lines, "outputSchema", ast.outputs);
    lines.push("");
  }

  // Wrap each typed tool's imported `run` body with the compiler-owned schema.
  for (const t of typedTools) {
    emitToolConst(lines, t);
    lines.push("");
  }

  lines.push(`export const ${ast.name}: ${agentType} = createAgent({`);
  lines.push(`  name: ${JSON.stringify(ast.name)},`);
  lines.push(`  model: ${JSON.stringify(ast.model)},`);
  if (ast.description !== undefined) {
    lines.push(`  description: ${JSON.stringify(ast.description)},`);
  }
  if (ast.maxTurns !== undefined) {
    lines.push(`  maxTurns: ${ast.maxTurns},`);
  }
  if (ast.maxContextTokens !== undefined) {
    lines.push(`  maxContextTokens: ${ast.maxContextTokens},`);
  }
  if (ast.retries !== undefined) {
    lines.push(`  retries: ${ast.retries},`);
  }
  if (ast.temperature !== undefined) {
    lines.push(`  temperature: ${ast.temperature},`);
  }
  const toolEntries = [
    ...ast.tools.map((t) =>
      t.input === undefined ? t.name : `${t.name}: ${t.name}Tool`,
    ),
    ...ast.uses.map((sub) => `${sub}: ${sub}.asTool()`),
  ];
  if (toolEntries.length > 0) {
    lines.push(`  tools: { ${toolEntries.join(", ")} },`);
  }
  if (hasInputs) {
    lines.push(`  inputSchema,`);
  }
  if (hasOutputs) {
    lines.push(`  outputSchema,`);
  }
  if (systemCode !== undefined) {
    lines.push(`  system: (inputs: ${inputType}) =>`);
    lines.push(`    ${systemCode},`);
  }
  lines.push(`  prompt: (inputs: ${inputType}) =>`);
  lines.push(`    ${promptCode},`);
  lines.push(`});`);
  lines.push("");
  lines.push(`export default ${ast.name};`);
  lines.push("");
  return lines.join("\n");
}

function emitInterface(
  lines: string[],
  name: string,
  fields: FieldDecl[],
): void {
  if (fields.length === 0) {
    lines.push(`export interface ${name} {}`);
    return;
  }
  lines.push(`export interface ${name} {`);
  for (const f of fields) {
    lines.push(
      `  ${f.name}${f.optional === true ? "?" : ""}: ${tsType(f.type)};`,
    );
  }
  lines.push(`}`);
}

function emitSchema(lines: string[], name: string, fields: FieldDecl[]): void {
  lines.push(`const ${name} = z.object({`);
  for (const f of fields) {
    const expr = zodExpr(f.type);
    lines.push(
      `  ${f.name}: ${f.optional === true ? `${expr}.optional()` : expr},`,
    );
  }
  lines.push(`});`);
}

/**
 * Emit a `defineTool` const wiring the declared input schema to the run body.
 * The explicit `<…Input>` type argument pins the input type to the declared
 * schema, so a `.tools.ts` body whose parameter type disagrees is a type error
 * (otherwise `defineTool` would infer the type from the body instead).
 */
function emitToolConst(lines: string[], t: ToolDecl): void {
  lines.push(`const ${t.name}Tool = defineTool<${pascalCase(t.name)}Input>({`);
  lines.push(`  description: ${JSON.stringify(t.description ?? t.name)},`);
  lines.push(`  input: ${zodExpr(t.input!)},`);
  lines.push(`  run: ${t.name},`);
  lines.push(`});`);
}

function tsType(t: ToaType): string {
  let base: string;
  if (t.base === "object") {
    base = `{ ${(t.fields ?? []).map((f) => `${f.name}: ${tsType(f.type)}`).join("; ")} }`;
  } else if (t.base === "enum") {
    base = (t.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
    // A union needs parens before `[]` to mean (a | b)[] rather than a | b[].
    if (t.array) base = `(${base})`;
  } else {
    base = t.base;
  }
  return t.array ? `${base}[]` : base;
}

function zodExpr(t: ToaType): string {
  let base: string;
  if (t.base === "object") {
    base = `z.object({ ${(t.fields ?? []).map((f) => `${f.name}: ${zodExpr(f.type)}`).join(", ")} })`;
  } else if (t.base === "enum") {
    base = `z.enum([${(t.values ?? []).map((v) => JSON.stringify(v)).join(", ")}])`;
  } else {
    base = `z.${t.base}()`;
  }
  return t.array ? `z.array(${base})` : base;
}

/** Codegen context: declared input types, and whether `toonValue` was emitted. */
interface EmitCtx {
  inputTypes: Map<string, ToaType>;
  /** Inputs declared with a trailing `?` — may be `undefined` at runtime. */
  optionalInputs: Set<string>;
  usesToon: boolean;
}

/** Whether a path roots at an optional input (`{inputs.x…}` with `x?,…`). */
function isOptionalInputRoot(path: string[], ctx: EmitCtx): boolean {
  return (
    path[0] === "inputs" && path.length >= 2 && ctx.optionalInputs.has(path[1]!)
  );
}

/**
 * The emitted expression for a path. Paths through an optional input use `?.`
 * after the root so field access stays safe when the input is omitted.
 */
function pathExpr(path: string[], ctx: EmitCtx): string {
  if (isOptionalInputRoot(path, ctx) && path.length > 2) {
    return `inputs.${path[1]}?.${path.slice(2).join(".")}`;
  }
  return path.join(".");
}

/** Walk a dotted path through object fields; returns the resolved type or null. */
function resolveFieldPath(type: ToaType, rest: string[]): ToaType | null {
  let cur = type;
  for (const seg of rest) {
    if (cur.array || cur.base !== "object" || cur.fields === undefined) {
      return null;
    }
    const field = cur.fields.find((f) => f.name === seg);
    if (field === undefined) return null;
    cur = field.type;
  }
  return cur;
}

/** The static type of an interpolation path, given inputs and loop bindings. */
function interpType(
  path: string[],
  ctx: EmitCtx,
  vars: Map<string, ToaType>,
): ToaType | null {
  const root = path[0];
  if (root !== undefined && vars.has(root)) {
    return resolveFieldPath(vars.get(root)!, path.slice(1));
  }
  if (root === "inputs" && path.length >= 2 && ctx.inputTypes.has(path[1]!)) {
    return resolveFieldPath(ctx.inputTypes.get(path[1]!)!, path.slice(2));
  }
  return null;
}

const isNonScalar = (t: ToaType): boolean => t.array || t.base === "object";

function promptExpr(
  segments: PromptSegment[],
  ctx: EmitCtx,
  vars: Map<string, ToaType>,
): string {
  return `\`${segmentsToBody(segments, ctx, vars)}\``;
}

function segmentsToBody(
  segments: PromptSegment[],
  ctx: EmitCtx,
  vars: Map<string, ToaType>,
): string {
  let out = "";
  for (const seg of segments) {
    if (seg.kind === "text") {
      out += escapeTemplate(seg.value);
    } else if (seg.kind === "interp") {
      if (seg.path[0] === "env") {
        out += `\${process.env.${seg.path.slice(1).join(".")} ?? ""}`;
      } else {
        const expr = pathExpr(seg.path, ctx);
        const type = interpType(seg.path, ctx, vars);
        // Non-scalar values (objects/arrays) render as TOON; scalars stay
        // plain. Optional scalars render as "" when omitted (toonValue already
        // renders undefined as "" for the non-scalar case).
        if (type !== null && isNonScalar(type)) {
          ctx.usesToon = true;
          out += `\${toonValue(${expr})}`;
        } else if (isOptionalInputRoot(seg.path, ctx)) {
          out += `\${${expr} ?? ""}`;
        } else {
          out += `\${${expr}}`;
        }
      }
    } else if (seg.kind === "each") {
      const bind =
        seg.item.kind === "name"
          ? seg.item.name
          : `{ ${seg.item.fields.join(", ")} }`;
      const params = seg.index !== undefined ? `${bind}, ${seg.index}` : bind;
      // Bind the loop variable(s) so references inside the body resolve their
      // types (and so object elements render as TOON). An optional array input
      // iterates as empty when omitted.
      const childVars = bindLoopVars(seg, ctx, vars);
      const src = isOptionalInputRoot(seg.source, ctx)
        ? `(${seg.source.join(".")} ?? [])`
        : seg.source.join(".");
      const loop = `${src}.map((${params}) => \`${segmentsToBody(seg.body, ctx, childVars)}\`).join("")`;
      out +=
        seg.else !== undefined && seg.else.length > 0
          ? `\${${src}.length > 0 ? ${loop} : \`${segmentsToBody(seg.else, ctx, vars)}\`}`
          : `\${${loop}}`;
    } else {
      const cond = `${seg.negate ? "!" : ""}${seg.cond.join(".")}`;
      out += `\${${cond} ? \`${segmentsToBody(seg.then, ctx, vars)}\` : \`${segmentsToBody(seg.else, ctx, vars)}\`}`;
    }
  }
  return out;
}

/** Extend `vars` with the binding(s) introduced by an `{#each}` loop. */
function bindLoopVars(
  seg: Extract<PromptSegment, { kind: "each" }>,
  ctx: EmitCtx,
  vars: Map<string, ToaType>,
): Map<string, ToaType> {
  const child = new Map(vars);
  const sourceType = interpType(seg.source, ctx, vars);
  if (sourceType === null || !sourceType.array) return child;
  const element: ToaType = { base: sourceType.base, array: false };
  if (sourceType.fields !== undefined) element.fields = sourceType.fields;
  if (seg.item.kind === "name") {
    child.set(seg.item.name, element);
  } else if (element.fields !== undefined) {
    for (const field of seg.item.fields) {
      const decl = element.fields.find((f) => f.name === field);
      if (decl !== undefined) child.set(field, decl.type);
    }
  }
  return child;
}

function escapeTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function pascalCase(name: string): string {
  return name
    .split(/[_\s]+/)
    .filter((s) => s.length > 0)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join("");
}
