import { describe, expect, it } from "vitest";
import { analyze } from "./analyze.js";
import { generate } from "./codegen.js";

const SOURCE = [
  "agent: researcher",
  "model: claude-opus-4-7",
  "description: Research a topic and return a sourced summary.",
  "inputs[1]{name,type}:",
  "  topic,string",
  "tools[2]: web_search,fetch_page",
  "prompt: |",
  "  You are a research analyst. Research: {inputs.topic}",
  "  Use web_search to find sources, then fetch_page to read them.",
  "  Return a cited summary.",
  "outputs[2]{name,type}:",
  "  summary,string",
  "  sources,string[]",
].join("\n");

// The canonical contract from _bmad-output/architecture.md §5.
const EXPECTED = `// Generated by toac from researcher.agent — do not edit.
import { createAgent, type Agent } from "@toad/runtime";
import { z } from "zod";
import { web_search, fetch_page } from "./researcher.tools";

export interface ResearcherInput {
  topic: string;
}

export interface ResearcherOutput {
  summary: string;
  sources: string[];
}

const inputSchema = z.object({
  topic: z.string(),
});

const outputSchema = z.object({
  summary: z.string(),
  sources: z.array(z.string()),
});

export const researcher: Agent<ResearcherInput, ResearcherOutput> = createAgent({
  name: "researcher",
  model: "claude-opus-4-7",
  description: "Research a topic and return a sourced summary.",
  tools: { web_search, fetch_page },
  inputSchema,
  outputSchema,
  prompt: (inputs: ResearcherInput) =>
    \`You are a research analyst. Research: \${inputs.topic}
Use web_search to find sources, then fetch_page to read them.
Return a cited summary.\`,
});

export default researcher;
`;

describe("generate — codegen contract", () => {
  it("emits the researcher.ts contract (architecture.md §5)", () => {
    const { ast, diagnostics } = analyze(SOURCE, "researcher.agent");
    expect(diagnostics).toEqual([]);
    expect(generate(ast!)).toBe(EXPECTED);
  });

  it("is deterministic", () => {
    const { ast } = analyze(SOURCE, "researcher.agent");
    expect(generate(ast!)).toBe(generate(ast!));
  });

  it("omits zod/tools and returns string output for a minimal agent", () => {
    const { ast } = analyze("agent: ping\nmodel: m\nprompt: hi", "ping.agent");
    const code = generate(ast!);
    expect(code).toContain("Agent<PingInput, string>");
    expect(code).not.toContain('from "zod"');
    expect(code).not.toContain("tools:");
  });
});
