import type { AgentAst, FieldDecl, PromptSegment, ToaType } from "./ast.js";

/**
 * Emit a readable, typed TypeScript module from an `AgentAst`. Output is
 * deterministic (same AST -> byte-identical code) and matches the contract in
 * `_bmad-output/architecture.md` §5. The emitted module imports its tools from
 * the co-located `<name>.tools` file and the loop from `@toa/runtime`.
 */
export function generate(ast: AgentAst): string {
  const pascal = pascalCase(ast.name);
  const inputType = `${pascal}Input`;
  const outputType = `${pascal}Output`;
  const hasInputs = ast.inputs.length > 0;
  const hasOutputs = ast.outputs.length > 0;
  const hasTools = ast.tools.length > 0;
  const agentType = `Agent<${inputType}, ${hasOutputs ? outputType : "string"}>`;

  const lines: string[] = [];
  lines.push(`// Generated by toac from ${ast.name}.agent — do not edit.`);
  lines.push(`import { createAgent, type Agent } from "@toa/runtime";`);
  if (hasInputs || hasOutputs) {
    lines.push(`import { z } from "zod";`);
  }
  if (hasTools) {
    lines.push(
      `import { ${ast.tools.join(", ")} } from "./${ast.name}.tools";`,
    );
  }
  for (const sub of ast.uses) {
    lines.push(`import { ${sub} } from "./${sub}";`);
  }
  lines.push("");

  emitInterface(lines, inputType, ast.inputs);
  lines.push("");

  if (hasOutputs) {
    emitInterface(lines, outputType, ast.outputs);
    lines.push("");
  }

  if (hasInputs) {
    emitSchema(lines, "inputSchema", ast.inputs);
    lines.push("");
  }

  if (hasOutputs) {
    emitSchema(lines, "outputSchema", ast.outputs);
    lines.push("");
  }

  lines.push(`export const ${ast.name}: ${agentType} = createAgent({`);
  lines.push(`  name: ${JSON.stringify(ast.name)},`);
  lines.push(`  model: ${JSON.stringify(ast.model)},`);
  if (ast.description !== undefined) {
    lines.push(`  description: ${JSON.stringify(ast.description)},`);
  }
  if (ast.maxTurns !== undefined) {
    lines.push(`  maxTurns: ${ast.maxTurns},`);
  }
  if (ast.retries !== undefined) {
    lines.push(`  retries: ${ast.retries},`);
  }
  const toolEntries = [
    ...ast.tools,
    ...ast.uses.map((sub) => `${sub}: ${sub}.asTool()`),
  ];
  if (toolEntries.length > 0) {
    lines.push(`  tools: { ${toolEntries.join(", ")} },`);
  }
  if (hasInputs) {
    lines.push(`  inputSchema,`);
  }
  if (hasOutputs) {
    lines.push(`  outputSchema,`);
  }
  lines.push(`  prompt: (inputs: ${inputType}) =>`);
  lines.push(`    ${promptExpr(ast.prompt)},`);
  lines.push(`});`);
  lines.push("");
  lines.push(`export default ${ast.name};`);
  lines.push("");
  return lines.join("\n");
}

function emitInterface(
  lines: string[],
  name: string,
  fields: FieldDecl[],
): void {
  if (fields.length === 0) {
    lines.push(`export interface ${name} {}`);
    return;
  }
  lines.push(`export interface ${name} {`);
  for (const f of fields) {
    lines.push(`  ${f.name}: ${tsType(f.type)};`);
  }
  lines.push(`}`);
}

function emitSchema(lines: string[], name: string, fields: FieldDecl[]): void {
  lines.push(`const ${name} = z.object({`);
  for (const f of fields) {
    lines.push(`  ${f.name}: ${zodExpr(f.type)},`);
  }
  lines.push(`});`);
}

function tsType(t: ToaType): string {
  const base =
    t.base === "object"
      ? `{ ${(t.fields ?? []).map((f) => `${f.name}: ${tsType(f.type)}`).join("; ")} }`
      : t.base;
  return t.array ? `${base}[]` : base;
}

function zodExpr(t: ToaType): string {
  const base =
    t.base === "object"
      ? `z.object({ ${(t.fields ?? []).map((f) => `${f.name}: ${zodExpr(f.type)}`).join(", ")} })`
      : `z.${t.base}()`;
  return t.array ? `z.array(${base})` : base;
}

function promptExpr(segments: PromptSegment[]): string {
  return `\`${segmentsToBody(segments)}\``;
}

function segmentsToBody(segments: PromptSegment[]): string {
  let out = "";
  for (const seg of segments) {
    if (seg.kind === "text") {
      out += escapeTemplate(seg.value);
    } else if (seg.kind === "interp") {
      out +=
        seg.path[0] === "env"
          ? `\${process.env.${seg.path.slice(1).join(".")} ?? ""}`
          : `\${${seg.path.join(".")}}`;
    } else if (seg.kind === "each") {
      const params =
        seg.index !== undefined ? `${seg.item}, ${seg.index}` : seg.item;
      const loop = `${seg.source.join(".")}.map((${params}) => \`${segmentsToBody(seg.body)}\`).join("")`;
      out +=
        seg.else !== undefined && seg.else.length > 0
          ? `\${${seg.source.join(".")}.length > 0 ? ${loop} : \`${segmentsToBody(seg.else)}\`}`
          : `\${${loop}}`;
    } else {
      const cond = `${seg.negate ? "!" : ""}${seg.cond.join(".")}`;
      out += `\${${cond} ? \`${segmentsToBody(seg.then)}\` : \`${segmentsToBody(seg.else)}\`}`;
    }
  }
  return out;
}

function escapeTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function pascalCase(name: string): string {
  return name
    .split(/[_\s]+/)
    .filter((s) => s.length > 0)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join("");
}
